import Script from "next/script";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Charts view",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script strategy="beforeInteractive" src="charting_library/charting_library.standalone.js" />
		  <Script strategy="beforeInteractive" src="datafeeds/udf/dist/bundle.js" />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
