import { getSymbolData } from "../../../be-api/getSymbolData";
import { NextRequest, NextResponse } from "next/server";

const dummySearchResult = {
  code: "0",
  remarks: "S",
  data: [
    {
      d_exch_t: "NSE",
      ISIN_code_s: "INE155A01022",
      NSE_Regular_lot_i: 1,
      ExchStatus_s: "A",
      OptType_s: "",
      volume_i: "12121719",
      Ticker_t: "TATAMOTORS",
      Inst_s: "EQUITY",
      disp_sym_s: "Tata Motors",
      Upper_ckt_d: 1069.65,
      Sym_t: "TATAMOTORS",
      id: "9743",
      Face_value_s: "2",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "EQ",
      customdatainst: "",
      Sid_s: "3456",
      disp_inst_s: "EQ",
      Strike_d: 0,
      MarketCap_d: "346212.25",
      isDetailedFNo_s: "false",
      exchInstname_s: "EQUITY",
      Sector_s: "Automobile",
      Seg_s: "E",
      MarketType_s: "Large Cap",
      ExchTradingSymbol_s: "TATAMOTORS",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "tata-motors-ltd",
      CompName_t: "Tata Motors",
      TradeSym_t: "TATAMOTORS-EQ",
      disp_inst_t: "EQ",
      ExpDate_s: "",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 875.2,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "",
      FreezeQty_i: 99685,
      _Exch_s: "NSE",
      LOT_UNITS_s: "",
    },
    {
      d_exch_t: "NSE",
      ISIN_code_s: "IN9155A01020",
      NSE_Regular_lot_i: 1,
      ExchStatus_s: "A",
      OptType_s: "",
      volume_i: "1981388",
      Ticker_t: "TATAMTRDVR",
      Inst_s: "EQUITY",
      disp_sym_s: "Tata Motors DVR",
      Upper_ckt_d: 772.25,
      Sym_t: "TATAMTRDVR",
      id: "7031",
      Face_value_s: "2",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "EQ",
      customdatainst: "",
      Sid_s: "16965",
      disp_inst_s: "EQ",
      Strike_d: 0,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "EQUITY",
      Sector_s: "",
      Seg_s: "E",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMTRDVR",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "tata-motors-dvr-ltd",
      CompName_t: "Tata Motors DVR",
      TradeSym_t: "TATAMTRDVR-EQ",
      disp_inst_t: "EQ",
      ExpDate_s: "",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 514.85,
      underlyingName: "TATAMTRDVR",
      UnderLyingId_s: "",
      FreezeQty_i: 155093,
      _Exch_s: "NSE",
      LOT_UNITS_s: "",
    },
    {
      d_exch_t: "BSE",
      ISIN_code_s: "INE155A01022",
      NSE_Regular_lot_i: 1,
      ExchStatus_s: "A",
      OptType_s: "",
      volume_i: "26916",
      Ticker_t: "TATAMOTORS",
      Inst_s: "EQUITY",
      disp_sym_s: "Tata Motors",
      Upper_ckt_d: 0,
      Sym_t: "TATAMOTORS",
      id: "243",
      Face_value_s: "2",
      d_exch: "BSE",
      SubSector_s: "-",
      Series_s: "EQ",
      customdatainst: "",
      Sid_s: "500570",
      disp_inst_s: "EQ",
      Strike_d: 0,
      MarketCap_d: "346212.25",
      isDetailedFNo_s: "false",
      exchInstname_s: "EQUITY",
      Sector_s: "Automobile",
      Seg_s: "E",
      MarketType_s: "Large Cap",
      ExchTradingSymbol_s: "TATAMOTORS",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "tata-motors-ltd",
      CompName_t: "Tata Motors",
      TradeSym_t: "TATAMOTORS-EQ",
      disp_inst_t: "EQ",
      ExpDate_s: "",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "",
      FreezeQty_i: -1,
      _Exch_s: "BSE",
      LOT_UNITS_s: "",
    },
    {
      d_exch_t: "BSE",
      ISIN_code_s: "IN9155A01020",
      NSE_Regular_lot_i: 1,
      ExchStatus_s: "A",
      OptType_s: "",
      volume_i: "3033",
      Ticker_t: "TATAMTRDVR",
      Inst_s: "EQUITY",
      disp_sym_s: "Tata Motors DVR",
      Upper_ckt_d: 0,
      Sym_t: "TATAMTRDVR",
      id: "4327",
      Face_value_s: "2",
      d_exch: "BSE",
      SubSector_s: "-",
      Series_s: "EQ",
      customdatainst: "",
      Sid_s: "570001",
      disp_inst_s: "EQ",
      Strike_d: 0,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "EQUITY",
      Sector_s: "",
      Seg_s: "E",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMTRDVR",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "tata-motors-dvr-ltd",
      CompName_t: "Tata Motors DVR",
      TradeSym_t: "TATAMTRDVR-EQ",
      disp_inst_t: "EQ",
      ExpDate_s: "",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0,
      underlyingName: "TATAMTRDVR",
      UnderLyingId_s: "",
      FreezeQty_i: -1,
      _Exch_s: "BSE",
      LOT_UNITS_s: "",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "XX",
      volume_i: "24458700",
      Ticker_t: "TATAMOTORS",
      Inst_s: "FUTSTK",
      disp_sym_s: "TATAMOTORS MAR FUT",
      Upper_ckt_d: 1044.45,
      Sym_t: "TATAMOTORS-Mar2024-FUT",
      id: "24004",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "FUT",
      customdatainst: "",
      Sid_s: "66519",
      disp_inst_s: "FUT",
      Strike_d: -0.01,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "FUTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MARFUT",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS MAR FUT",
      TradeSym_t: "TATAMOTORS-Mar2024-FUT-FUT",
      disp_inst_t: "FUT",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 854.55,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "XX",
      volume_i: "4461675",
      Ticker_t: "TATAMOTORS",
      Inst_s: "FUTSTK",
      disp_sym_s: "TATAMOTORS APR FUT",
      Upper_ckt_d: 1052,
      Sym_t: "TATAMOTORS-Apr2024-FUT",
      id: "66168",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "FUT",
      customdatainst: "",
      Sid_s: "67108",
      disp_inst_s: "FUT",
      Strike_d: -0.01,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "FUTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24APRFUT",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS APR FUT",
      TradeSym_t: "TATAMOTORS-Apr2024-FUT-FUT",
      disp_inst_t: "FUT",
      ExpDate_s: "2024-04-25 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 860.75,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "XX",
      volume_i: "434625",
      Ticker_t: "TATAMOTORS",
      Inst_s: "FUTSTK",
      disp_sym_s: "TATAMOTORS MAY FUT",
      Upper_ckt_d: 1061.8,
      Sym_t: "TATAMOTORS-May2024-FUT",
      id: "98566",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "FUT",
      customdatainst: "",
      Sid_s: "56400",
      disp_inst_s: "FUT",
      Strike_d: -0.01,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "FUTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAYFUT",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS MAY FUT",
      TradeSym_t: "TATAMOTORS-May2024-FUT-FUT",
      disp_inst_t: "FUT",
      ExpDate_s: "2024-05-30 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 868.75,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "30784275",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 1000 CALL",
      Upper_ckt_d: 16.3,
      Sym_t: "TATAMOTORS-Mar2024-1000-CE",
      id: "14117",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195113",
      disp_inst_s: "OP",
      Strike_d: 1000,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR1000CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 1000 CALL",
      TradeSym_t: "TATAMOTORS-Mar2024-1000-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "19854525",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 980 CALL",
      Upper_ckt_d: 25.35,
      Sym_t: "TATAMOTORS-Mar2024-980-CE",
      id: "14113",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195109",
      disp_inst_s: "OP",
      Strike_d: 980,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR980CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 980 CALL",
      TradeSym_t: "TATAMOTORS-Mar2024-980-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "19201875",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 970 CALL",
      Upper_ckt_d: 31.4,
      Sym_t: "TATAMOTORS-Mar2024-970-CE",
      id: "14095",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195107",
      disp_inst_s: "OP",
      Strike_d: 970,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR970CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 970 CALL",
      TradeSym_t: "TATAMOTORS-Mar2024-970-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "17632950",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 960 CALL",
      Upper_ckt_d: 38.55,
      Sym_t: "TATAMOTORS-Mar2024-960-CE",
      id: "14109",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195105",
      disp_inst_s: "OP",
      Strike_d: 960,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR960CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 960 CALL",
      TradeSym_t: "TATAMOTORS-Mar2024-960-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "PE",
      volume_i: "14537850",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 950 PUT",
      Upper_ckt_d: 46.35,
      Sym_t: "TATAMOTORS-Mar2024-950-PE",
      id: "14108",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195104",
      disp_inst_s: "OP",
      Strike_d: 950,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR950PE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 950 PUT",
      TradeSym_t: "TATAMOTORS-Mar2024-950-PE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "12180900",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 990 CALL",
      Upper_ckt_d: 20.5,
      Sym_t: "TATAMOTORS-Mar2024-990-CE",
      id: "14115",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195111",
      disp_inst_s: "OP",
      Strike_d: 990,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR990CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 990 CALL",
      TradeSym_t: "TATAMOTORS-Mar2024-990-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "10351200",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 950 CALL",
      Upper_ckt_d: 46.55,
      Sym_t: "TATAMOTORS-Mar2024-950-CE",
      id: "14107",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195103",
      disp_inst_s: "OP",
      Strike_d: 950,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR950CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 950 CALL",
      TradeSym_t: "TATAMOTORS-Mar2024-950-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "10147425",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 1050 CALL",
      Upper_ckt_d: 5.5,
      Sym_t: "TATAMOTORS-Mar2024-1050-CE",
      id: "14143",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195123",
      disp_inst_s: "OP",
      Strike_d: 1050,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR1050CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 1050 CALL",
      TradeSym_t: "TATAMOTORS-Mar2024-1050-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "9536100",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 1010 CALL",
      Upper_ckt_d: 12.85,
      Sym_t: "TATAMOTORS-Mar2024-1010-CE",
      id: "14119",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195115",
      disp_inst_s: "OP",
      Strike_d: 1010,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR1010CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 1010 CALL",
      TradeSym_t: "TATAMOTORS-Mar2024-1010-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "PE",
      volume_i: "9087225",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 960 PUT",
      Upper_ckt_d: 54.45,
      Sym_t: "TATAMOTORS-Mar2024-960-PE",
      id: "14110",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195106",
      disp_inst_s: "OP",
      Strike_d: 960,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR960PE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 960 PUT",
      TradeSym_t: "TATAMOTORS-Mar2024-960-PE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "8666850",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 1020 CALL",
      Upper_ckt_d: 10.1,
      Sym_t: "TATAMOTORS-Mar2024-1020-CE",
      id: "14121",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195117",
      disp_inst_s: "OP",
      Strike_d: 1020,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR1020CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 1020 CALL",
      TradeSym_t: "TATAMOTORS-Mar2024-1020-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "PE",
      volume_i: "8370450",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 940 PUT",
      Upper_ckt_d: 38.7,
      Sym_t: "TATAMOTORS-Mar2024-940-PE",
      id: "14106",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195102",
      disp_inst_s: "OP",
      Strike_d: 940,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR940PE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 940 PUT",
      TradeSym_t: "TATAMOTORS-Mar2024-940-PE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "7585275",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 1100 CALL",
      Upper_ckt_d: 4.35,
      Sym_t: "TATAMOTORS-Mar2024-1100-CE",
      id: "21652",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "47271",
      disp_inst_s: "OP",
      Strike_d: 1100,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR1100CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 1100 CALL",
      TradeSym_t: "TATAMOTORS-Mar2024-1100-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "PE",
      volume_i: "7164900",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 900 PUT",
      Upper_ckt_d: 15.15,
      Sym_t: "TATAMOTORS-Mar2024-900-PE",
      id: "14098",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195094",
      disp_inst_s: "OP",
      Strike_d: 900,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR900PE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 900 PUT",
      TradeSym_t: "TATAMOTORS-Mar2024-900-PE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "PE",
      volume_i: "6988200",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 920 PUT",
      Upper_ckt_d: 24.7,
      Sym_t: "TATAMOTORS-Mar2024-920-PE",
      id: "14102",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195098",
      disp_inst_s: "OP",
      Strike_d: 920,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR920PE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 920 PUT",
      TradeSym_t: "TATAMOTORS-Mar2024-920-PE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "PE",
      volume_i: "6285675",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 930 PUT",
      Upper_ckt_d: 31,
      Sym_t: "TATAMOTORS-Mar2024-930-PE",
      id: "14104",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195100",
      disp_inst_s: "OP",
      Strike_d: 930,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR930PE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 930 PUT",
      TradeSym_t: "TATAMOTORS-Mar2024-930-PE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "4605600",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 1040 CALL",
      Upper_ckt_d: 6.25,
      Sym_t: "TATAMOTORS-Mar2024-1040-CE",
      id: "14125",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195121",
      disp_inst_s: "OP",
      Strike_d: 1040,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR1040CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 1040 CALL",
      TradeSym_t: "TATAMOTORS-Mar2024-1040-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "PE",
      volume_i: "4411800",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 970 PUT",
      Upper_ckt_d: 64.35,
      Sym_t: "TATAMOTORS-Mar2024-970-PE",
      id: "14112",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195108",
      disp_inst_s: "OP",
      Strike_d: 970,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR970PE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 970 PUT",
      TradeSym_t: "TATAMOTORS-Mar2024-970-PE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "4128225",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 1030 CALL",
      Upper_ckt_d: 7.9,
      Sym_t: "TATAMOTORS-Mar2024-1030-CE",
      id: "14123",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195119",
      disp_inst_s: "OP",
      Strike_d: 1030,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR1030CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 1030 CALL",
      TradeSym_t: "TATAMOTORS-Mar2024-1030-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "3732075",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 1060 CALL",
      Upper_ckt_d: 5.15,
      Sym_t: "TATAMOTORS-Mar2024-1060-CE",
      id: "11997",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "38047",
      disp_inst_s: "OP",
      Strike_d: 1060,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR1060CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 1060 CALL",
      TradeSym_t: "TATAMOTORS-Mar2024-1060-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "PE",
      volume_i: "3320250",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 910 PUT",
      Upper_ckt_d: 19.35,
      Sym_t: "TATAMOTORS-Mar2024-910-PE",
      id: "14100",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195096",
      disp_inst_s: "OP",
      Strike_d: 910,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR910PE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 910 PUT",
      TradeSym_t: "TATAMOTORS-Mar2024-910-PE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "2743125",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 940 CALL",
      Upper_ckt_d: 55.15,
      Sym_t: "TATAMOTORS-Mar2024-940-CE",
      id: "14105",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195101",
      disp_inst_s: "OP",
      Strike_d: 940,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR940CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 940 CALL",
      TradeSym_t: "TATAMOTORS-Mar2024-940-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "2460975",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 1070 CALL",
      Upper_ckt_d: 4.9,
      Sym_t: "TATAMOTORS-Mar2024-1070-CE",
      id: "12040",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "38078",
      disp_inst_s: "OP",
      Strike_d: 1070,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR1070CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 1070 CALL",
      TradeSym_t: "TATAMOTORS-Mar2024-1070-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "2248650",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 1080 CALL",
      Upper_ckt_d: 4.65,
      Sym_t: "TATAMOTORS-Mar2024-1080-CE",
      id: "12022",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "38093",
      disp_inst_s: "OP",
      Strike_d: 1080,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR1080CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 1080 CALL",
      TradeSym_t: "TATAMOTORS-Mar2024-1080-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "2221575",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 25 APR 1000 CALL",
      Upper_ckt_d: 41.35,
      Sym_t: "TATAMOTORS-Apr2024-1000-CE",
      id: "64605",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "132736",
      disp_inst_s: "OP",
      Strike_d: 1000,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24APR1000CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 25 APR 1000 CALL",
      TradeSym_t: "TATAMOTORS-Apr2024-1000-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-04-25 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 4.85,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "PE",
      volume_i: "2187375",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 880 PUT",
      Upper_ckt_d: 8.55,
      Sym_t: "TATAMOTORS-Mar2024-880-PE",
      id: "14158",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195090",
      disp_inst_s: "OP",
      Strike_d: 880,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR880PE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 880 PUT",
      TradeSym_t: "TATAMOTORS-Mar2024-880-PE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "PE",
      volume_i: "1586025",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 980 PUT",
      Upper_ckt_d: 75.05,
      Sym_t: "TATAMOTORS-Mar2024-980-PE",
      id: "14114",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195110",
      disp_inst_s: "OP",
      Strike_d: 980,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR980PE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 980 PUT",
      TradeSym_t: "TATAMOTORS-Mar2024-980-PE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 3.35,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "PE",
      volume_i: "1436400",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 890 PUT",
      Upper_ckt_d: 11.5,
      Sym_t: "TATAMOTORS-Mar2024-890-PE",
      id: "14096",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195092",
      disp_inst_s: "OP",
      Strike_d: 890,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR890PE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 890 PUT",
      TradeSym_t: "TATAMOTORS-Mar2024-890-PE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "1397925",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 25 APR 1100 CALL",
      Upper_ckt_d: 12.4,
      Sym_t: "TATAMOTORS-Apr2024-1100-CE",
      id: "78226",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "39923",
      disp_inst_s: "OP",
      Strike_d: 1100,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24APR1100CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 25 APR 1100 CALL",
      TradeSym_t: "TATAMOTORS-Apr2024-1100-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-04-25 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.9,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "PE",
      volume_i: "1353750",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 850 PUT",
      Upper_ckt_d: 4.35,
      Sym_t: "TATAMOTORS-Mar2024-850-PE",
      id: "14152",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195084",
      disp_inst_s: "OP",
      Strike_d: 850,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR850PE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 850 PUT",
      TradeSym_t: "TATAMOTORS-Mar2024-850-PE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "PE",
      volume_i: "1338075",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 1000 PUT",
      Upper_ckt_d: 97.05,
      Sym_t: "TATAMOTORS-Mar2024-1000-PE",
      id: "14118",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195114",
      disp_inst_s: "OP",
      Strike_d: 1000,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR1000PE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 1000 PUT",
      TradeSym_t: "TATAMOTORS-Mar2024-1000-PE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 14.55,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "PE",
      volume_i: "1206975",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 25 APR 900 PUT",
      Upper_ckt_d: 30.6,
      Sym_t: "TATAMOTORS-Apr2024-900-PE",
      id: "64577",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "132727",
      disp_inst_s: "OP",
      Strike_d: 900,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24APR900PE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 25 APR 900 PUT",
      TradeSym_t: "TATAMOTORS-Apr2024-900-PE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-04-25 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 1.4,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "1102950",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 25 APR 1050 CALL",
      Upper_ckt_d: 23.05,
      Sym_t: "TATAMOTORS-Apr2024-1050-CE",
      id: "52629",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "138301",
      disp_inst_s: "OP",
      Strike_d: 1050,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24APR1050CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 25 APR 1050 CALL",
      TradeSym_t: "TATAMOTORS-Apr2024-1050-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-04-25 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 1.45,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "953325",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 1180 CALL",
      Upper_ckt_d: 3.6,
      Sym_t: "TATAMOTORS-Mar2024-1180-CE",
      id: "36410",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "132640",
      disp_inst_s: "OP",
      Strike_d: 1180,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR1180CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 1180 CALL",
      TradeSym_t: "TATAMOTORS-Mar2024-1180-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "PE",
      volume_i: "943350",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 870 PUT",
      Upper_ckt_d: 6.15,
      Sym_t: "TATAMOTORS-Mar2024-870-PE",
      id: "14156",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195088",
      disp_inst_s: "OP",
      Strike_d: 870,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR870PE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 870 PUT",
      TradeSym_t: "TATAMOTORS-Mar2024-870-PE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "872100",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 25 APR 1080 CALL",
      Upper_ckt_d: 16.1,
      Sym_t: "TATAMOTORS-Apr2024-1080-CE",
      id: "64512",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "132756",
      disp_inst_s: "OP",
      Strike_d: 1080,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24APR1080CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 25 APR 1080 CALL",
      TradeSym_t: "TATAMOTORS-Apr2024-1080-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-04-25 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 1.1,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "845025",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 1150 CALL",
      Upper_ckt_d: 3.8,
      Sym_t: "TATAMOTORS-Mar2024-1150-CE",
      id: "20631",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "45265",
      disp_inst_s: "OP",
      Strike_d: 1150,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR1150CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 1150 CALL",
      TradeSym_t: "TATAMOTORS-Mar2024-1150-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "760950",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 1120 CALL",
      Upper_ckt_d: 4.1,
      Sym_t: "TATAMOTORS-Mar2024-1120-CE",
      id: "8689",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "54787",
      disp_inst_s: "OP",
      Strike_d: 1120,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR1120CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 1120 CALL",
      TradeSym_t: "TATAMOTORS-Mar2024-1120-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "PE",
      volume_i: "716775",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 860 PUT",
      Upper_ckt_d: 4.8,
      Sym_t: "TATAMOTORS-Mar2024-860-PE",
      id: "14154",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195086",
      disp_inst_s: "OP",
      Strike_d: 860,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR860PE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 860 PUT",
      TradeSym_t: "TATAMOTORS-Mar2024-860-PE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "688275",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 1090 CALL",
      Upper_ckt_d: 4.5,
      Sym_t: "TATAMOTORS-Mar2024-1090-CE",
      id: "22098",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "41512",
      disp_inst_s: "OP",
      Strike_d: 1090,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR1090CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 1090 CALL",
      TradeSym_t: "TATAMOTORS-Mar2024-1090-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "672600",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 1110 CALL",
      Upper_ckt_d: 4.2,
      Sym_t: "TATAMOTORS-Mar2024-1110-CE",
      id: "8478",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "53878",
      disp_inst_s: "OP",
      Strike_d: 1110,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR1110CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 1110 CALL",
      TradeSym_t: "TATAMOTORS-Mar2024-1110-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "CE",
      volume_i: "584250",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 1130 CALL",
      Upper_ckt_d: 3.95,
      Sym_t: "TATAMOTORS-Mar2024-1130-CE",
      id: "20629",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "45263",
      disp_inst_s: "OP",
      Strike_d: 1130,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR1130CE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 1130 CALL",
      TradeSym_t: "TATAMOTORS-Mar2024-1130-CE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
    {
      d_exch_t: "NSE",
      exp_type_s: "M",
      ISIN_code_s: "",
      NSE_Regular_lot_i: 1425,
      ExchStatus_s: "A",
      OptType_s: "PE",
      volume_i: "542925",
      Ticker_t: "TATAMOTORS",
      Inst_s: "OPTSTK",
      disp_sym_s: "TATAMOTORS 28 MAR 840 PUT",
      Upper_ckt_d: 4.05,
      Sym_t: "TATAMOTORS-Mar2024-840-PE",
      id: "14150",
      Face_value_s: "",
      d_exch: "NSE",
      SubSector_s: "-",
      Series_s: "OP",
      customdatainst: "",
      Sid_s: "195082",
      disp_inst_s: "OP",
      Strike_d: 840,
      MarketCap_d: "",
      isDetailedFNo_s: "false",
      exchInstname_s: "OPTSTK",
      Sector_s: "",
      Seg_s: "D",
      MarketType_s: "",
      ExchTradingSymbol_s: "TATAMOTORS24MAR840PE",
      NSE_tick_size_d: 0.05,
      Seo_symbol_s: "",
      CompName_t: "TATAMOTORS 28 MAR 840 PUT",
      TradeSym_t: "TATAMOTORS-Mar2024-840-PE-OP",
      disp_inst_t: "OP",
      ExpDate_s: "2024-03-28 14:30:00",
      Mcx_Multiplier_i: 1,
      LoweCkt_d: 0.05,
      underlyingName: "TATAMOTORS",
      UnderLyingId_s: "3456",
      FreezeQty_i: 28501,
      _Exch_s: "NSE",
      LOT_UNITS_s: "1425 Qty",
    },
  ],
};

export async function GET(request: NextRequest) {
  const symbol: string = request.nextUrl.searchParams.get("symbol") || "";
  if (!symbol) {
    return NextResponse.json({
      err: "Please provide the symbol",
    });
  }
  const searchResult = dummySearchResult ;
  return NextResponse.json(searchResult);
}
